# Local config example for LangOS
# Copy/rename to .langos-local.yaml to override; .langos.yaml is the fallback.
# doc_roots is a map of business/background docs directories relative to the langos repo root (use ../ for siblings).
doc_roots:
  langos-docs: ../langos-docs/
active_doc_root: langos-docs
