id: add_requirement
name: 添加新需求规格文档
version: 3
description: >
  将用户的一句话想法或详细描述，结合现有项目背景，通过对话引导整理成结构化的需求规格文档，
  存放到当前会话选定的业务文档库（doc_root）下的 specs/ 目录。

triggers:
  - user_intent: "add_new_requirement"
  - user_utterance_contains:
      - "添加新需求"
      - "帮我写一个需求 spec"
      - "我想做一个新功能"
      - "帮我把这个需求梳理成文档"

preconditions:
  - "doc_root 已选定且可访问（如未选定，先按启动引导的 doc_roots 选择/新增流程确认）。"

outputs:
  - "文档存放路径与文件名建议。"
  - "结构化的需求规格草稿。"
  - "待确认的细节或 TODO。"

steps:
  - id: load_context
    type: ANALYZE_DOCS
    instruction: >
      确保已选定 doc_root；若未设置或目录不存在，先提示用户选择/新增（接受 `name: path` 并可调用 init-doc-root），再继续。
      在开始提问前，先快速阅读 doc_root 下的基础信息，建立上下文感：
      1. 读取 `repos/INDEX.md`（如有）：了解当前有哪些活跃仓库/模块，以便推断用户可能针对哪个项目。
      2. 读取 `blueprints/vision.md` 或 `README.md`（如有）：了解项目的整体技术风格和愿景。
      3. 读取 `specs/` 下最近的几个文件名：了解大家通常怎么命名文件。
      
      **不要输出任何内容给用户**，这一步是你的“预习”阶段。

  - id: analyze_and_explore
    type: ASK_USER
    instruction: >
      基于用户的初始输入 **+ 刚才预习到的上下文** 进行引导：
      
      1. **关于目标项目**：
         - 如果用户没说项目，且 `repos/INDEX.md` 里有多个项目，**列出它们**供用户选择（例如：“是针对 langos 内核，还是 demo-app？”），而不是泛泛地问“目标项目是什么”。
         - 如果用户没说项目，且 `repos/` 下只有一个主项目，直接**推断**是该项目并求证。
      
      2. **关于需求引导**：
         - 扮演产品经理，结合项目愿景（blueprints）进行追问。
         - 如果输入简略，进行交互式引导（核心价值、边界情况）。
      
      目标：把对话聊得像“老员工”之间的沟通，而不是“填表机器人”。

  - id: structure_and_plan
    type: PLAN_DOCS
    instruction: >
      基于沟通结果，主动设计文档结构和文件名。
      参考 `specs/` 下已有的命名习惯给出建议路径（如 specs/<repo>/YYYYMM-feature.md）。
      请用户确认结构。

  - id: draft_spec
    type: DRAFT_DOCS
    instruction: >
      按确认的结构起草文档。
      - 自动将口语转化为书面语。
      - 对于未确定的细节，根据项目背景（blueprints）给出**合理的默认值**并标记 TODO，减少用户输入负担。
      展示草稿供用户审阅。

  - id: finalize
    type: CONFIRM_AND_SUMMARIZE
    instruction: >
      确认并列出最终将写入的文件路径。
      (用户确认后才执行写入)

safety:
  - "对话与输出全程使用中文。"
  - "充分利用 doc_root 已有信息，避免问用户显而易见的问题（如‘我们有哪些项目’）。"
  - "未经确认不得直接写入文件。"
  - "路径与命名遵守 runtime/conventions.md。"
