id: add_requirement
name: 添加新需求规格文档
version: 2
description: >
  将用户的一句话想法或详细描述，通过对话引导整理成结构化的需求规格文档，
  存放到业务文档库（doc_root）下的 specs/ 目录。

triggers:
  - user_intent: "add_new_requirement"
  - user_utterance_contains:
      - "添加新需求"
      - "帮我写一个需求 spec"
      - "我想做一个新功能"
      - "帮我把这个需求梳理成文档"

preconditions:
  - "用户提供了初步的想法或需求描述。"
  - "允许在 doc_root/specs/ 下创建或更新文档。"

outputs:
  - "文档存放路径与文件名建议。"
  - "结构化的需求规格草稿（自动补全背景、范围、逻辑等）。"
  - "待确认的细节或 TODO。"

steps:
  - id: analyze_and_explore
    type: ASK_USER
    instruction: >
      分析用户的初始输入：
      1. **若输入详细**（包含目标/逻辑/边界）：直接总结要点，确认我理解是否正确，即可进入下一步。
      2. **若输入简略**（如“我想加个登录”）：扮演产品经理角色，进行**交互式引导**。
         - 不要一次性抛出所有问题。
         - 针对核心价值、用户场景、边界情况（不做白名单、不做复杂权限等）进行追问。
         - 提出你的建议（例如“建议先做 MVP，暂不考虑 xxxx”）。
      目标是把“一句话”聊成“一个清晰的方案轮廓”，待用户觉得聊得差不多了，再进行汇总。

  - id: structure_and_plan
    type: PLAN_DOCS
    instruction: >
      基于刚才的沟通，**由 AI 主动**设计文档结构和文件名，而不要问用户“你要分几节”。
      推荐结构（可视情况增减）：
      - 背景与目标（Why & What）
      - 核心逻辑/功能点（How）
      - 边界与非目标（What not to do）
      - 数据/接口/依赖（Technical constraints）
      - 验收标准（Success metrics）
      
      给出建议的存放路径（如 specs/<repo>/YYYYMM-feature.md），请用户确认结构是否合理。

  - id: draft_spec
    type: DRAFT_DOCS
    instruction: >
      按确认的结构起草文档，**自动将对话中的口语转化为书面语**。
      - 对话中未确定的细节，不要留空，根据惯例给出**“推荐默认值”**并标记为 (待确认) 或 TODO。
      - 确保文档包含 metadata（状态：草稿，创建日期等）。
      展示草稿内容供用户审阅。

  - id: finalize
    type: CONFIRM_AND_SUMMARIZE
    instruction: >
      确认用户对草稿满意。
      - 若用户有修改意见，快速调整并重新展示。
      - 最终确认后，列出将写入的文件路径。
      - (用户确认后才执行写入操作)

safety:
  - "对话与输出全程使用中文，保持产品经理般的引导感，而非填表机器。"
  - "未经确认不得直接写入文件；遇到模糊信息可先由 AI 预设建议方案供用户拍板。"
  - "路径与命名遵守 runtime/conventions.md。"
