id: add_protocol
name: 添加指令
version: 1
description: >
  通过与用户对话，定义、创建或修改一条 AI 协议（YAML 文件），
  并在用户确认后将该协议登记到 langos/runtime/protocols/index.yaml 中，
  使其可以被自然语言请求自动匹配和调用。

triggers:
  - user_intent: "add_new_protocol"
  - user_utterance_contains:
      - "添加一个新的 AI 协议"
      - "帮我定义一条新的指令"
      - "我想新增一种操作流程"
      - "给 AI 多加一个能力"

preconditions:
  - "用户表述了希望 AI 以后能重复执行的一类典型操作。"
  - "当前 index.yaml 中还没有一条完全匹配的协议，或者用户明确表示要修改/替换现有协议。"

outputs:
  - "一份新的或更新后的协议 YAML 草稿，例如 langos/runtime/protocols/<id>.yaml 的完整内容。"
  - "对 index.yaml 的更新建议：新增或修改一个 protocols 条目。"

steps:
  - id: clarify_need
    type: ASK_USER
    instruction: >
      向用户澄清这条新指令/协议的意图和使用场景，至少包括：
      - 用户希望在什么场景使用它（典型输入是什么）；
      - 希望 AI 做到的结果（典型输出是什么）；
      - 是否有必须遵守的约束（例如必须先征得确认、不能自动修改文件等）；
      - 预期这条协议会被多频繁地用到、是否值得固化。
      提问应尽量结构化，并在问完一轮后用列表形式小结当前理解，
      请用户确认是否继续补充或已经足够。

  - id: check_existing_protocols
    type: ANALYZE_PROTOCOLS
    instruction: >
      查看 langos/runtime/protocols/index.yaml 中已有的协议列表，
      判断是否已经存在一条涵盖同类场景的协议：
      - 如存在高度重合的协议，向用户说明重叠之处，并询问是要扩展/修改原协议，
        还是依然创建一条全新的协议；
      - 如不存在合适协议，则继续按“新增协议”的路径进行。
      将你的判断结果明确说明给用户，并征求选择。

  - id: design_protocol_shape
    type: PLAN_PROTOCOL
    instruction: >
      基于用户确认的需求和现有协议情况，设计新协议的基本结构，包括：
      - 协议 id（仅包含小写字母、数字和下划线，具有清晰语义）；
      - name（中文名，简洁明了）；
      - 一个简短的 description；
      - 触发方式（triggers）：intent 名称 + 若干自然语言例句；
      - 关键步骤列表（steps），每一步的目的和类型（ASK_USER / ANALYZE_* / DRAFT_DOCS / AWAIT_AND_APPLY 等）。
      将这一“草案结构”以列表形式展示给用户，请用户确认或调整，
      在获得确认前不要生成最终 YAML。

  - id: draft_yaml
    type: DRAFT_DOCS
    instruction: >
      在协议结构获得用户确认后，生成完整的协议 YAML 草稿，
      字段通常包括：
      - id / name / version / description
      - triggers / preconditions / outputs
      - steps（包含 id / type / instruction）
      - safety（需要特别强调的约束）
      输出时应给出完整的 YAML 文本，准备写入 langos/runtime/protocols/<id>.yaml，
      并提醒用户这是“草稿版本，尚未最终生效”。

  - id: review_and_refine
    type: AWAIT_AND_APPLY
    instruction: >
      邀请用户对协议草稿进行逐条审阅：
      - 如用户提出修改意见，按意见调整 YAML 内容并再次展示；
      - 必要时，可进一步拆分步骤或补充 safety 约束；
      - 当用户明确表示“可以”或“通过”后，才视为该协议的正式版本。
      在此阶段，不要自动对 index.yaml 做任何更新操作，只给出“建议更新内容”。

  - id: propose_index_update
    type: PLAN_INDEX_UPDATE
    instruction: >
      基于最终版协议内容，为 index.yaml 生成一段建议的新增/修改条目，
      典型结构为：
      - id / name / file / description
      - triggers.intent
      - triggers.utterance_examples
      将该条目以 YAML 片段的形式展示给用户，
      明确说明“这是需要添加到 langos/runtime/protocols/index.yaml 的内容”。

  - id: finalize
    type: CONFIRM_AND_SUMMARIZE
    instruction: >
      在协议本身和 index.yaml 更新条目都获得用户确认后，
      用简要列表总结：
      - 协议 id 和用途；
      - 建议写入的协议文件路径（langos/runtime/protocols/<id>.yaml）；
      - 建议追加/更新的 index.yaml 片段。
      提醒用户在实际文件系统中完成：
      1）创建/更新协议 YAML 文件；
      2）在 index.yaml 中追加或修改对应条目；
      3）后续可以通过自然语言触发该协议。
      不要假设这些文件已经自动写入，除非用户或外部系统明确执行了保存操作。

safety:
  - "不得在用户没有明确要求的情况下，删除或彻底改写现有协议。"
  - "如新协议与现有协议高度重合，应优先询问用户是否合并或扩展，而不是盲目新增。"
  - "在协议设计中，遇到业务含义不清楚的地方，必须向用户提问，不得自行编造。"
  - "只有在用户明确表示接受后，才视为协议和 index.yaml 更新方案最终确定。"
