id: doc_ops
name: 文档操作（单入口）
role: governance
version: 1
description: >
  面向 doc_root 的文档操作统一入口，覆盖“新增文档（create）/小补丁（patch）/整理修订（groom）”三类诉求，
  默认 dry-run，只输出计划与草稿，任何写入/移动/重命名/归档前必须经用户明确确认。

triggers:
  - user_intent: "doc_ops"
  - user_utterance_contains:
      - "整理文档"
      - "修订文档"
      - "补几行文档"
      - "改下文档"
      - "新增文档"
      - "写个 spec"
      - "归档文档"

preconditions:
  - "doc_root 已选定且可访问；如未选定，先按启动引导选择/新增（可调用 init_doc_root），再继续。"
  - "默认不落盘：在用户确认前，不写入/移动/重命名/归档任何文件。"
  - "若用户需求本质是“对照代码更新文档”，建议切换到 refresh_repo_docs（但不强制）。"

outputs:
  - "动作类型判定：create / patch / groom，以及判定依据。"
  - "目标范围清单：涉及的文件/目录及 SOT 文件标记。"
  - "变更计划：逐文件要改什么、为什么、风险与强动作提示。"
  - "草稿/补丁：可复制的新文档草稿或补丁片段（保持 dry-run）。"
  - "强确认清单：写入/重命名/移动/批量操作等需显式确认的项。"

steps:
  - id: classify_request
    type: ASK_USER
    instruction: >
      1) 根据用户表述初判动作类型（create/patch/groom），说明判定依据，提供选择或调整；如用户关注“对照代码更新文档”，提示可用 refresh_repo_docs（不强制切换）。
      2) 约定默认 dry-run，不落盘；若用户期望写入，先收集显式授权。
      3) 信息收集：
         - create：确认目标目录（如 specs/<repo>/、adr/、projects/…）、命名偏好；命名建议遵守 meta/conventions.md（如 specs 默认 `YYYYMMDD-topic-spec.md`）。
         - patch：要求明确目标文件路径与定位锚点（章节名/关键词/上下文），缺少则先补足再继续。
         - groom：确认希望覆盖的范围（目录/文件类型）与优先级（SOT 对齐/去重/补状态链路/归档候选等）。

  - id: inventory_scope
    type: ANALYZE_DOCS
    instruction: >
      在确认的范围内盘点文件，标注 SOT 优先级：
      1) 校验 doc_root 是否可访问，不可用则提示先走 doc_root 选择/新增。
      2) 列出涉及的文件/目录（含缺失项），标注 SOT（如 runtime/guidelines.md、runtime/runtime.md、runtime/conventions.md 以及 doc_root 内 meta/conventions.md、repos/INDEX.md 等）。
      3) 不输出长摘要，仅给出清单与缺项提示，供后续计划使用。

  - id: plan_work
    type: PLAN_DOCS
    instruction: >
      基于盘点结果规划具体动作，并标注强确认项：
      - create：给出路径与命名建议（遵循规范），说明命名理由；列出需要同步的导航/索引文件（如 repos/INDEX.md、目录 README）。
      - patch：列出要改的段落/小节与预期锚点，说明目的与风险；如锚点不足，先补锚点再起草。
      - groom：列出需要回收进 SOT 的修改点（如对齐 meta/conventions.md）、重复/冲突点、spec 状态链路补齐、归档候选；明确“不执行移动/重命名，只给候选”。
      - 强动作（写入/移动/重命名/批量修改）需单独列清并等待确认；未确认前不得进入执行。

  - id: draft_output
    type: DRAFT_DOCS
    instruction: >
      按确认的计划生成可复制的草稿/补丁，保持 dry-run：
      - create：输出完整文档草稿（含 TODO），标注预期路径。
      - patch/groom：输出包含上下文锚点的补丁片段；groom 另给归档候选清单和 SOT/状态链路补丁。
      - 不执行任何写入、移动或重命名；如需归档/迁移，仅给出建议与补丁。

  - id: confirm_and_summarize
    type: CONFIRM_AND_SUMMARIZE
    instruction: >
      汇总：动作类型、涉及文件与操作、草稿/补丁位置、导航更新片段、强确认清单。
      明确“尚未写入/移动/重命名/归档”，征求最终确认或交由用户手动落盘；记录未决事项。

safety:
  - "全程中文，对路径/代码保持原文。"
  - "默认 dry-run，未经用户明确同意不得写入/移动/重命名/归档。"
  - "patch 必须有明确锚点，锚点不足时先澄清。"
  - "命名/结构遵守 runtime/conventions.md 及 doc_root 的 meta/conventions.md。"
  - "若发现请求超出协议（如需要 init_doc_root 或 refresh_repo_docs），先提示并征求是否切换。"
  - "避免大范围扫描/输出冗长摘要，聚焦清单与可执行片段。"
