id: simulate_protocol
name: 协议模拟与验收
version: 1
description: >
  在不产生实际副作用（不写入文件）的情况下，扮演用户与 AI
  进行多轮对话，验证某个新协议或修改后的协议是否符合预期。
  这是“自举”开发中的单元测试步骤。

triggers:
  - user_intent: "test_protocol"
  - user_utterance_contains:
      - "模拟运行一下这个协议"
      - "测试一下新写的指令"
      - "验证一下刚才的修改"

preconditions:
  - "已明确目标协议的来源：内存中的草稿 YAML，或 `runtime/protocols/<id>.yaml` 等已存在文件。"

outputs:
  - "模拟对话记录（Transcript）。"
  - "验收结论（Pass/Fail）。"
  - "修正建议与后续动作。"

steps:
  - id: setup_simulation
    type: ASK_USER
    instruction: >
      确认要测试的目标协议：提供协议来源（内存草稿、协议 ID、或文件路径），以及预期覆盖的场景。
      设定测试输入：写出模拟用户的触发话术/上下文（如缺省路径、是否有业务目录）。

  - id: role_play_loop
    type: SIMULATION
    instruction: >
      进入“双重人格”模式：
      1. **测试员（User Sim）**：根据设定场景，模拟用户发指令。
      2. **执行器（System Sim）**：严格按照目标协议的 steps 执行，输出每一步的思考和回应。
      **注意**：在模拟过程中，遇到 `DRAFT_DOCS` 或 `WRITE_FILE` 步骤时，
      仅输出“（模拟写入：xxx.md）”，**绝对不要**进行实际文件操作。
      如协议需要确认或多轮收集信息，按步骤逐一展开，必要时补充多组测试话术。

  - id: analyze_result
    type: ANALYZE_LOGIC
    instruction: >
      检查模拟过程是否顺畅：
      - 是否陷入死循环？
      - 是否正确收集了所有必要信息？
      - 是否触发了 safety 拦截？
      输出测试结论。

  - id: summarize_and_next
    type: CONFIRM_AND_SUMMARIZE
    instruction: >
      汇总此次模拟的 Pass/Fail、发现的问题和修正建议，明确后续动作（如更新协议草稿、重跑模拟、再提交 index）。
      确认用户是否接受结论与下一步。

safety:
  - "模拟过程中严禁写入磁盘。"
  - "如果模拟的是核心路由协议（dispatch_request），需格外小心，防止测试员指令被外层真实系统捕获。"
